## ---- 开发环境 ---- ##
opsli:
  prefix: api
  version: v1


# 端口设置
server:
  port: 8080

spring:
  # 邮件设置
  mail:
    host: smtp.qq.com
    username: meet.parker@foxmail.com
    password: pamjnijkjkqdbbea
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
#  ## quartz定时任务,采用数据库方式
#  quartz:
#    job-store-type: jdbc

  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: '123456'
    port: 6379
  # 数据库配置
  datasource:
    # 数据库连接池监控
    druid:
      stat-view-servlet:
        # 数据库监控开关
        enabled: true
        # 登录用户名/密码
        login-username: admin
        login-password: 123456
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow:
        # IP 黑名单，若白名单也存在，则优先使用
        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
    # 多数据源
    dynamic:
      druid:
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #主数据源
      #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      #primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/opsli-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          username: root
          password: 12345678
          driver-class-name: com.mysql.jdbc.Driver
        # 多数据源配置
        #multi-datasource1:
          #url: jdbc:mysql://localhost:3306/opsli-boot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
          #username: root
          #password: 12345678
          #driver-class-name: com.mysql.jdbc.Driver

#Mybatis输出sql日志
logging:
  level:
    org.opsli.modulars.system.mapper : debug

# swagger 配置
swagger:
  production: false